file = {
	'ldoc/init.lua',
	'ldoc/Language.lua',
	'ldoc/Node.lua',
	'ldoc/Parser.lua',
	'ldoc/Point.lua',
	'ldoc/Query.lua',
	'ldoc/QueryCapture.lua',
	'ldoc/QueryCursor.lua',
	'ldoc/QueryMatch.lua',
	'ldoc/Range.lua',
	'ldoc/RangeArray.lua',
	'ldoc/Tree.lua',
}
project = 'lua-tree-sitter'
description = 'Lua bindings for Tree-sitter'
title = 'lua-tree-sitter Reference'
dir = 'doc'
format = 'markdown'
